version: 0.1

env:
  parameter-store:
    REGISTRY_URL: "/codebuild/dns/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    DHCP_DNS_TERRAFORM_OUTPUTS: "/terraform_dns_dhcp/$ENV/outputs"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  build:
    commands:
      - make authenticate-docker
      - make publish
      - make deploy
