version: 0.1

env:
  variables:
    AWS_REGION: eu-west-2
  parameter-store:
    ROLE_ARN: /codebuild/pttp-ci-infrastructure-core-pipeline/development/assume_role # tests hardcoded to only run in development

phases:
  install:
    commands:
      - echo nope

  build:
    commands:
      - make test
