version: "3"
services:
  dns:
    build:
      context: ./dns-service
    environment:
      LOCAL_DEVELOPMENT: "true"
      DNS_HEALTH_CHECK_URL: "foobar.com"
    volumes:
      - ./dns-service/test_named.conf:/home/named.conf
      - ./dns-service/metrics/:/home/metrics
      - ./dns-service/zones:/etc/bind/zones
    ports:
      - "127.0.0.1:80:80"
  dns-test:
    build:
      context: ./dns-service
      args:
        EXTRA_BUNDLE_CONFIG: ""
    depends_on:
      - dns
    volumes:
      - ./scripts/test.sh:/home/dns_test.sh
      - ./dns-service/test_queryfile:/home/test_queryfile
      - ./dns-service/metrics/:/home/metrics
