version: '3'
services:
  dns:
    build: ./dns-service
    environment:
      LOCAL_DEVELOPMENT: "true"
    volumes:
      - ./dns-service/test_named.conf:/home/named.conf

  dns-test:
    build: ./dns-service
    depends_on:
      - dns
    volumes:
      - ./scripts/test:/home/dns_test
      - ./dns-service/test_queryfile:/home/test_queryfile
