version: "3"
services:
  dns:
    build:
      context: ./dns-service
    environment:
      LOCAL_DEVELOPMENT: "true"
    volumes:
      - ./dns-service/test_named.conf:/home/named.conf
      - ./dns-service/metrics/:/home/metrics
      - ./dns-service/zones:/etc/bind/zones

  dns-perf:
    build:
      context: ./dns-local-load-testing
    depends_on:
      - dns
    volumes:
      - ./dns-service/test_named.conf:/home/named.conf
      - ./dns-local-load-testing/1k_queryfile:/home/1k_queryfile

  dns-test:
    build:
      context: ./dns-service
      args:
        EXTRA_BUNDLE_CONFIG: ""
    depends_on:
      - dns
    volumes:
      - ./scripts/test.sh:/home/dns_test.sh
      - ./dns-service/test_queryfile:/home/test_queryfile
      - ./dns-service/metrics/:/home/metrics
