version: "3"
services:
  dns:
    build: ./dns-service
    environment:
      LOCAL_DEVELOPMENT: "true"
    volumes:
      - ./dns-service/test_named.conf:/home/named.conf
      - ./dns-service/metrics/:/home/metrics

  dns-test:
    build:
      context: ./dns-service
      args:
        EXTRA_BUNDLE_CONFIG: ""
    depends_on:
      - dns
    volumes:
      - ./scripts/test:/home/dns_test
      - ./dns-service/test_queryfile:/home/test_queryfile
      - ./dns-service/metrics/:/home/metrics
